invoicemanager-master/invoicemanager/urls.py
from django.urls import path

from . import views

app_name = "invoicemanager"
urlpatterns = [

	# # # DEFAULT

	path('', views.invoices.index, name='index'),

    # # # INVOICES

    path('invoice/new/', views.invoices.new_invoice, name='new_invoice'),
    path('invoice/all/', views.invoices.all_invoices, name='all_invoices'),
    path('invoice/draft/', views.invoices.draft_invoices, name='draft_invoices'),
    path('invoice/paid/', views.invoices.paid_invoices, name='paid_invoices'),
    path('invoice/unpaid/', views.invoices.unpaid_invoices, name='unpaid_invoices'),
    path('invoice/<int:invoice_id>/', views.invoices.invoice, name='invoice'),
    path('invoice/search/', views.invoices.search_invoice, name='search_invoice'),
    path('invoice/<int:invoice_id>/update/', views.invoices.update_invoice, name='update_invoice'),
    path('invoice/<int:invoice_id>/print/', views.invoices.print_invoice, name='print_invoice'),
    path('invoice/<int:invoice_id>/delete/', views.invoices.delete_invoice, name='delete_invoice'),


    # # # ITEMS

    path('invoice/<int:invoice_id>/item/add/', views.items.add_item, name='add_item'),
    path('invoice/<int:invoice_id>/item/<int:invoiceitem_id>/delete/', views.items.delete_item, name='delete_item'),

    # # # INVOICE EXPENSES

    path('invoice/<int:invoice_id>/expenses/add/', views.expenses.add_invoice_expense, name='add_invoice_expense'),
    path('invoice/<int:invoice_id>/expenses/<int:expense_id>/delete/', views.expenses.delete_invoice_expense, name='delete_invoice_expense'),

    # # # BUSINESS EXPENSES

    path('expenses/', views.expenses.expense_list, name='expense_list'),
    path('expenses/new/', views.expenses.new_business_expense, name='new_business_expense'),
    path('expenses/<int:expense_id>/delete/', views.expenses.delete_business_expense, name='delete_business_expense'),

    # # # REPORTS

    path('accounting/', views.reports.accounting, name='accounting'),

    # # # ATTACHMENTS

    path('invoice/<int:invoice_id>/attachments/add/', views.invoices.upload_invoice_attachment, name='upload_invoice_attachment'),
    path('invoice/<int:invoice_id>/attachments/<int:invoiceattachment_id>/delete/', views.invoices.delete_invoice_attachment, name='delete_invoice_attachment'),
    path('expenses/<int:expense_id>/attachments/add/', views.expenses.upload_business_expense_attachment, name='upload_business_expense_attachment'),

    # # # CUSTOMERS

    path('customers/', views.customers.customer_list, name='customer_list'),
    path('customer/<int:customer_id>/', views.customers.customer, name='customer'),
	path('customer/<int:customer_id>/update/', views.customers.update_customer, name='update_customer'),
    path('customer/<int:customer_id>/delete/', views.customers.delete_customer, name='delete_customer'),
    path('customer/new/', views.customers.new_customer, name='new_customer'),

    ############for finance ####################
 # # # INVOICES

    path('invoicea/new/', views.invoiceas.new_invoicea, name='new_invoicea'),
    path('invoicea/all/', views.invoiceas.all_invoiceas, name='all_invoiceas'),
    path('invoicea/draft/', views.invoiceas.draft_invoiceas, name='draft_invoiceas'),
    path('invoicea/paid/', views.invoiceas.paid_invoiceas, name='paid_invoiceas'),
    path('invoicea/unpaid/', views.invoiceas.unpaid_invoiceas, name='unpaid_invoiceas'),
    path('invoicea/<int:invoicea_id>/', views.invoiceas.invoicea, name='invoicea'),
    path('invoicea/search/', views.invoiceas.search_invoicea, name='search_invoicea'),
    path('invoicea/<int:invoicea_id>/update/', views.invoiceas.update_invoicea, name='update_invoicea'),
    path('invoicea/<int:invoicea_id>/print/', views.invoiceas.print_invoicea, name='print_invoicea'),
    path('invoicea/<int:invoicea_id>/delete/', views.invoiceas.delete_invoicea, name='delete_invoicea'),

    # # # ITEMS

    path('invoicea/<int:invoicea_id>/itema/add/', views.itemas.add_itema, name='add_itema'),
    path('invoicea/<int:invoicea_id>/itema/<int:invoiceitema_id>/delete/', views.itemas.delete_itema, name='delete_itema'),

    # # # INVOICE EXPENSES

    path('invoicea/<int:invoicea_id>/expenseas/add/', views.expenseas.add_invoicea_expensea, name='add_invoicea_expensea'),
    path('invoicea/<int:invoicea_id>/expenseas/<int:expensea_id>/delete/', views.expenseas.delete_invoicea_expensea, name='delete_invoicea_expensea'),

    # # # BUSINESS EXPENSES

    path('expenseas/', views.expenseas.expensea_list, name='expensea_list'),
    path('expenseas/new/', views.expenseas.new_business_expensea, name='new_business_expensea'),
    path('expenseas/<int:expensea_id>/delete/', views.expenseas.delete_business_expensea, name='delete_business_expensea'),

    # # # REPORTS

    path('accounting/', views.reportas.accounting, name='accounting'),


    # # # CUSTOMERS

    path('customeras/', views.customeras.customera_list, name='customera_list'),
    path('customera/<int:customera_id>/', views.customeras.customera, name='customera'),
	path('customera/<int:customera_id>/update/', views.customeras.update_customera, name='update_customera'),
    path('customera/<int:customera_id>/delete/', views.customeras.delete_customera, name='delete_customera'),
    path('customera/new/', views.customeras.new_customera, name='new_customera'),


    # # # USER AUTHENTICATION

    path('login/', views.userauth.login_view, name='login'),
    path('logout/', views.userauth.logout_view, name='logout'),

    # # # ADMIN

    path('users/', views.admin.users, name='users'),
    path('settings/', views.admin.settings, name='settings'),
]

invoicemanager-master/invoicemanager/models.py
from __future__ import unicode_literals

import decimal
from datetime import datetime

from django.core.files.storage import FileSystemStorage
from django.db import models
from datetime import date
from tkinter import IntVar
import math
from decimal import Decimal


# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=256)
    address = models.CharField(max_length=256, blank=True)
    number = models.CharField(max_length=128, blank=True)
    email = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.name

    def invoices(self):
	    return Invoice.objects.filter(customer=self).count()


class Invoice(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateField()
    status = models.CharField(max_length=10)

    def total_days(self):
        items = InvoiceItem.objects.filter(invoice_id=self.id)
        for item in items:
            diff = (date.today() - item.ddate).days
            diff = int(diff)
            return diff
    def rate(self):
        if self.total_days() <= 30:
            rate = 24
        elif self.total_days() > 30 and self.total_days() <= 90:
            rate = 27
        elif self.total_days() > 90 and self.total_days() <= 180:
            rate = 30
        else:
            rate = 36
        return rate

    def interest(self):
        time = self.total_days()
        rate = self.rate()
        items = InvoiceItem.objects.filter(invoice_id=self.id)
        for item in items:
            intres = time * rate * item.money
            intres = intres/3600
        return intres

    def total_amount(self):
        t_amount = 0
        items = InvoiceItem.objects.filter(invoice_id=self.id)
        for item in items:
            t_amount += item.money
        return t_amount

    def remaining_amount(self):
        amount = self.total_amount()
        expenses = Expense.objects.filter(invoice_id=self.id)
        for expense in expenses:
            r_amount = amount - expense.pamount
        return r_amount


    def total_due(self):
        amount = self.remaining_amount()
        interest = self.remaining_interest()
        total = amount + interest
        return total

    def total_day(self):
        total_d = 0
        items = InvoiceItem.objects.filter(invoice_id=self.id)
        for item in items:
            total_d = item.tdays()
        return total_d
    def i_rate(self):
        r = 0
        items = InvoiceItem.objects.filter(invoice_id=self.id)
        for item in items:
            r = item.rate()
        return r
    def i_interest(self):
        inte = 0
        items = InvoiceItem.objects.filter(invoice_id=self.id)
        for item in items:
            inte = item.interest()
        return inte
    def total_a(self):
        amount = self.total_amount()
        interest = self.i_interest()
        total = amount + interest
        return total
    def name(self):
        items = InvoiceItem.objects.filter(invoice_id=self.id)
        for item in items:
            name = item.name
        return name

    def total_interest(self):
        sum = 0
        items = InvoiceItem.objects.filter(invoice_id=self.id)
        for item in items:
            sum += item.interest()
        return sum

    def remaining_interest(self):
        interest = self.i_interest()
        expenses = Expense.objects.filter(invoice_id=self.id)
        for expense in expenses:
            interest -= expense.pinterest

        return interest








    # def total_days(self):
    #     date1 = self.withdrawn_date()
    #     date2 = self.deposite_date()
    #     diff = (date1 - date2).days
    #     diff = int(diff)
    #     return diff


    def __str__(self):
        return str(self.id)

    # def amount(self):
    #     total = 0
    #     items = self.invoiceitem_set.all()
    #     for item in items:
    #         total = total + item.money
    #     self.save()
    #     return total

    # def interes(self):
    #     tinterest = 0
    #     items = InvoiceItem.objects.filter(invoice_id=self.id)
    #     for item in items:
    #         tinterest += item.interest()
    #     return tinterest
    #
    # def total_amount(self):
    #     tinterest = self.interes()
    #     tamount = self.amount()
    #     sum = tinterest + tamount
    #     return sum
    #
    # def total_interest(self):
    #     t_interest = 0
    #     items = Invoice.objects.filter(id=self.id)
    #     for item in items:
    #         t_interest += item.interes()
    #     return t_interest


    def paid(self):
        return self.status == 'Paid'

    def unpaid(self):
        return self.status == 'Unpaid'

    def draft(self):
        return self.status == 'Draft'

class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    money = models.IntegerField(default=0)
    weight = models.IntegerField(default=0)
    ddate = models.DateField(blank=True, null=True)



    def tdays(self):
        diff = (date.today() - self.ddate).days
        diff = int(diff)
        return diff

    def rate(self):
        if self.tdays() <= 30:
            rate = 24
        elif self.tdays() > 30 and self.tdays() <= 180:
            rate = 27
        elif self.tdays() > 180 and self.tdays() <= 365:
            rate = 30

        else:
            rate = 36
        return rate

    def interest(self):
        p = self.money
        t = self.tdays()
        r = self.rate()
        interes = (p * t * r)/36000
        return interes

    # def rate(self):
    #     diff = self.tdays()
    #     if diff < 30 or diff == 30:
    #         rate = 24
    #         return rate
    #
    #     elif diff > 30 and diff < 180:
    #         rate = 27
    #         return rate
    #     else:
    #         rate = 30
    #         return rate
    #
    # def interest(self):
    #     diff = self.tdays()
    #     rate = self.rate()
    #     if rate == 24:
    #         si = (diff * 24 * self.money) / 36000
    #
    #     elif rate == 27:
    #
    #         si = (diff * 27 * self.money) / 36000
    #     # return float(si)
    #     else:
    #         si = (diff * 30 * self.money) / 36000
    #     # self.save()
    #     return round(si, 2)
    #

class Expense(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField()
    wdate = models.DateField(blank=True, null=True)
    pamount = models.IntegerField(blank=True, null=True)
    pinterest = models.IntegerField(blank=True, null=True)

    # def t_amount(self):
    #     items = Invoice.objects.filter(id=self.id)
    #     for item in items:
    #         global s_amount
    #         s_amount = item.total_amount()
    #     return "hello"
    #
    # def remaining_amount(self):
    #     r_amount = 0
    #     items = Invoice.objects.filter(id=self.id)
    #     for item in items:
    #         r_amount = item.amount() - self.pamount
    #     return r_amount
    #
    # def remaining_interest(self):
    #     r_interest = 0
    #     items = Invoice.objects.filter(id=self.id)
    #     for item in items:
    #         r_interest = item.interes() - self.pinterest
    #     return r_interest
    #
    # def due(self):
    #     due_interest = self.remaining_interest()
    #     due_amount = self.remaining_amount()
    #     sum = due_amount + due_interest
    #     return sum

    def is_business_expense(self):
        return self.invoice is None


class InvoiceAttachment(models.Model):
    file = models.FileField(upload_to='invoice/')
    displayname = models.CharField(max_length=128)
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)


class ExpenseAttachment(models.Model):
    file = models.FileField(upload_to='expense/')
    displayname = models.CharField(max_length=128)
    expense = models.ForeignKey(Expense, on_delete=models.CASCADE)







###################################### for the finance ################################
# Create your models here.
class Customera(models.Model):
    name = models.CharField(max_length=256)
    address = models.CharField(max_length=256, blank=True)
    number = models.CharField(max_length=128, blank=True)
    email = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.name

    def invoiceas(self):
        return Invoicea.objects.filter(customera=self).count()


class Invoicea(models.Model):
    customera = models.ForeignKey(Customera, on_delete=models.CASCADE)
    date = models.DateField()
    status = models.CharField(max_length=10)


    def name(self):
        items = InvoiceItema.objects.filter(invoicea_id=self.id)
        for item in items:
            name = item.name
            return name

    def total_days(self):
        items = InvoiceItema.objects.filter(invoicea_id=self.id)
        for item in items:
            diff = (date.today() - item.ddate).days
            diff = int(diff)
            return diff

    def rate(self):
        items = InvoiceItema.objects.filter(invoicea_id=self.id)
        for item in items:
            rate_r = item.rate
            return rate_r

    def interest(self):
        inte = 0
        items = InvoiceItema.objects.filter(invoicea_id=self.id)
        for item in items:
            inte = item.interest()
        return round(inte, 2)

    def total_interest(self):
        interest = 0
        items = InvoiceItema.objects.filter(invoicea_id=self.id)
        for item in items:
            interest += item.interest()
        return interest

    def amount(self):
        items = self.invoiceitema_set.all()
        amount = 0
        for item in items:
            amount = item.amount
            return amount

    def total_due(self):
        amount = self.amount()
        items = Invoice.objects.filter(id=self.id)
        for item in items:

invoicemanager-master/invoicemanager/views/admin.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
import datetime

from invoicemanager.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment,  Customera, Invoicea, InvoiceItema, Expensea, InvoiceAttachmenta, ExpenseAttachmenta



# Administrative settings
def users(request):
    return None


def settings(request):
    return None

invoicemanager-master/invoicemanager/views/itemas.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from invoicemanager.models import Customera, Invoicea, InvoiceItema, Expensea, InvoiceAttachmenta, ExpenseAttachmenta



# Add invoiceitem to invoice
@login_required(login_url='login/')
def add_itema(request, invoicea_id):
	invoicea = get_object_or_404(Invoicea, pk=invoicea_id)
	try:
		i = invoicea.invoiceitema_set.create(name=request.POST['name'], amount=request.POST['amount'], ddate=request.POST['ddate'], rate=request.POST['rate'])
		i.save()
	except (KeyError, Invoicea.DoesNotExist):
		return render(request, 'view_invoicea.html', {
			'invoicea': invoicea,
			'error_message': 'Not all fields were completed.',
		})
	else:
		return HttpResponseRedirect(reverse('invoicea', args=(invoicea.id,)))



# Delete invoiceitem from invoice
@login_required(login_url='login/')
def delete_itema(request, invoiceitema_id, invoicea_id):

	itema = get_object_or_404(InvoiceItema, pk=invoiceitema_id)
	invoicea = get_object_or_404(Invoicea, pk=invoicea_id)
	try:
		itema.delete()
	except (KeyError, InvoiceItema.DoesNotExist):
		return render(request, 'view_invoicea.html', {
			'invoicea': invoicea,
			'error_message': 'Item does not exist.',
		})
	else:
		return HttpResponseRedirect(reverse('invoicea', args=(invoicea.id,)))

invoicemanager-master/invoicemanager/templates/invoice.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}

<div class="alert alert-danger">{{ error_message }}</div>

{% endif %}

{% if invoice %}
<!-- Display invoice -->

<h2 class="text-center">Invoice {{ customer.id }}</h2>

<!-- Customer information -->

<form method="POST" action="{% url 'update_invoice' invoice.id %}" name="customer" class="form-horizontal">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Customer</div>
		<div class="panel-body">
			<div class="form-group">
				<label class="col-sm-3 control-label">Customer:</label>
				<div class="col-sm-6">
					<p class="form-control-static"><a href="{% url 'customer' invoice.customer.id %}">{{ invoice.customer.name }}</a></p>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Date:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="date" id="invoicedate" value="{{ invoice.date|date:"SHORT_DATE_FORMAT"}}">
				</div>
				<script type="text/javascript">
					$(function () {
						$('#invoicedate').datepicker({
							todayBtn: "linked",
							orientation: "bottom left",
							autoclose: true
						});
					});
					</script>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Status:</label>
				<div class="col-sm-6">
					<select name="status" class="form-control">
						<option value="Draft" {% if invoice.draft %}selected{% endif %}>Draft</option>
						<option value="Paid" {% if invoice.paid %}selected{% endif %}>Paid</option>
						<option value="Unpaid" {% if invoice.unpaid %}selected{% endif %}>Unpaid</option>
					<select>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<input type="submit" value="Save" class="btn btn-primary">
			<a href="{% url 'print_invoice' invoice.id %}" target="_new" class="btn btn-default">Printable Invoice</a>
		</div>
	</div>
</form>

<!-- END Customer information -->

<!-- Invoice items -->

<form action="{% url 'add_item' invoice.id %}" method="post" class="form-inline">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Invoice items</div>
		<table class="table table-hover">
			<tr>
				<th>Item</th>
				<th>Weight(In gm)</th>
				<th>Money</th>
				<th>Deposited Date</th>
				<th class="text-right">Actions</th>
			</tr>
			{% for item in invoice.invoiceitem_set.all %}
			<tr>
				<td>{{ item.name }}</td>
				<td>{{ item.weight }}Gm</td>
				<td>RS{{item.money }}</td>
				<td>{{ item.ddate }}</td>
				<td class="text-right">
					<button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ item.name }}" data-delete-url="{% url 'delete_item' invoice.id item.id %}">Delete</button>
				</td>
			</tr>
			{% endfor %}
			<tr>
				<td><input type="text" name="name" class="form-control"></td>
				<td>
					<div class="input-group"><input type="text" name="weight" class="form-control" placeholder="0.00"/><span class="input-group-addon">gm</span></div>
				</td>
				<td>
					<div class="input-group"><span class="input-group-addon">Rs</span><input type="text" name="money" class="form-control" placeholder="0.00"/></div>
				</td>
				<td><input type="text" value="" name="date" class="bod-picker" placeholder="enter deposite date"></td>
				<td class="text-right">
					<input type="submit" class="btn btn-xs btn-primary" value="Save">
				</td>
			</tr>
		</table>
		<div class="panel-footer text-right"><strong>Total: Rs{{ invoice.total_amount }}</strong></div>
	</div>
</form>

<form action="{% url 'add_invoice_expense' invoice.id %}" method="post" class="form-inline">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Invoice expenses</div>
		<table class="table table-hover">
			<tr>
				<th>Description</th>
				<th>Paid Interest</th>
				<th>Paid Amount</th>
				<th>total days</th>
				<th>interest rate</th>
				<th>Total Amount</th>
				<th>Total Interest</th>
				<th>Remaining Amount</th>
				<th>Remaining Interest</th>
				<th>Total Due</th>
				<th class="text-right">Actions</th>
			</tr>
			{% for expense in invoice.expense_set.all %}
			<tr>
				<td>{{ expense.description }}</td>
				<td>Rs{{ expense.pinterest }}</td>
				<td>Rs{{ expense.pamount }}</td>
				<td>{{ invoice.total_days }}</td>
				<td>{{ invoice.rate }}%</td>
				<td>{{ invoice.total_amount }}</td>
				<td>{{ invoice.i_interest }}</td>
				<td>{{ invoice.remaining_amount }}</td>
				<td>{{ invoice.remaining_interest }}</td>
				<td>{{ invoice.total_due }}</td>
				<td class="text-right">
					<button type="button" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ expense.description }}" data-delete-url="{% url 'delete_invoice_expense' invoice.id expense.id %}">Delete</button>
				</td>
			</tr>
			{% endfor %}
			<tr>
				<td><input type="text" name="description" class="form-control"></td>
				<td>
					<div class="input-group"><span class="input-group-addon">Rs</span><input type="text" name="pinterest" class="form-control" placeholder="0.00"/></div>
				</td>
				<td>
					<div class="input-group"><span class="input-group-addon">Rs</span><input type="text" name="pamount" class="form-control" placeholder="0.00"/></div>
				</td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td class="text-right">
					<input type="submit" class="btn btn-xs btn-primary" value="Add">
				</td>
			</tr>
		</table>
<!--		<div class="panel-footer text-right"><strong>Total: ${{ invoice.total_expenses }}</strong></div>-->
	</div>
</form>

<form action="{% url 'upload_invoice_attachment' invoice.id %}" method="POST" enctype="multipart/form-data" class="form-inline">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading" >Attachments</div>
		<table class="table table-hover">
			<tr>
				<th>File</th>
				<th class="text-right">Actions</th>
			</tr>
			{% for attachment in invoice.invoiceattachment_set.all %}
			<tr>
				<td><a href="{{ attachment.file.url }}">{{ attachment.displayname }}</a></td>
				<td class="text-right">
					<button type="button" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ attachment.displayname }}" data-delete-url="{% url 'delete_invoice_attachment' invoice.id attachment.id %}" class="btn btn-xs btn-danger">Delete</button>
				</td>
			</tr>
			{% endfor %}
			<tr>
				<td>
					<input type="file" class="file col-sm-6" name="file" id="file" data-show-preview="false">
				</td>
				<td class="text-right">
					<input type="submit" class="btn btn-xs btn-primary" value="Upload">
				</td>
			</tr>
		</table>
	</div>
</form>

<div class="well text-right">Invoice net total: ${{ invoice.total }}</div>


<!-- Delete confirmation modal -->
<div class="modal fade" id="confirmdelete" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Confirm</h4>
			</div>
			<div class="modal-body">

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">No</button>
				<a href="#" class="btn btn-danger">Yes</a>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
		$('#confirmdelete').on('show.bs.modal', function(e) {
			var name = $(e.relatedTarget).data('object-name');
			var url = $(e.relatedTarget).data('delete-url');
			$('#confirmdelete .modal-body').text("Are you sure you want to delete " + name + "?");
			$('#confirmdelete .modal-footer a').attr('href', url);
		});
	});
</script>
<!-- END delete confirmation modal -->



{% if confirm_update %}
<!-- Update success modal -->
<div class="modal fade" id="updateconfirm" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-body">
			<h4>Changes saved!</h4>
        </div>
        <div class="modal-footer">
			<a href="#" data-dismiss="modal" class="btn btn-primary">Ok</a>
        </div>
      </div>
    </div>
</div>

<!-- Trigger success confirmation modal -->
<script>
$(document).ready(function(){
	$("#updateconfirm").modal();
});
</script>
<!-- End success confirmation modal -->
{% endif %}

<!-- End display invoice -->

{% else %}
<!-- Display invoice error -->

<div class="alert alert-warning">Invoice number not found!</div>

<!-- End display invoice error -->
{% endif %}

{% endblock %}

invoicemanager-master/invoicemanager/templates/new_customer.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger">{{ error_message }}</div>
{% endif %}

<form method="POST" action="" name="customer" class="form-horizontal">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">New Customer</div>
		<div class="panel-body">
			<div class="form-group">
				<label class="col-sm-3 control-label">Customer Name:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="name" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Address:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="address" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Phone Number:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="number" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Email:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="email" />
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<input type="submit" name="savecreate" value="Save and Create Invoice" class="btn btn-default">
			<input type="submit" name="save" value="Save" class="btn btn-primary">
		</div>
	</div>
</form>

{% endblock %}